### ISSUE TITLE
[FEATURE REQUEST] Android Auto & others

### ISSUE THREAD

**Issue by Xraifoo** [namidaco/namida#335] opened 2024-09-01 01:41 UTC
Android auto support? Would love to use it as it's a very big thing for me when I'm driving, adds more quality of life. Additionally, I previously requested a swipe to queue feature, is it possible to add vibration feedback with an intensity slider as an option? Just adds an assurance that the track is actively being selected. Another great feature for that swipe feature is the amount that we need to slide to queue something.

**Comment by MSOB7YY** [comment] 2024-09-01 10:45
lmaooo i literally just added support for Android Auto moments ago, im not sure if it will detect normally since i think apps should only get installed from google play in order to be detected.
also the queue system needs many changes (basically maintaining the queue for android side and not just the app one) so im still not sure yet

>  is it possible to add vibration feedback with an intensity slider as an option?

it already vibrates when a swipe action is done. separate option for vibration intensity is not welcomed 


> Another great feature for that swipe feature is the amount that we need to slide to queue something.

the amount needed in order for the action to register is [0.1 or 10% of the total track length](https://github.com/namidaco/namida/blob/c0ace9468586e546ba803e4e8749b7003d1cfe85/lib/ui/widgets/library/track_tile.dart#L573). again option for that is not welcomed. unnecessary bloat


btw android auto request is a duplicate of #157, so am gonna close this ^^

**Closed** 2024-09-01 18:51 UTC
