### ISSUE TITLE
[FEATURE REQUEST] Sort tracks in playlist

### ISSUE THREAD

**Issue by z9xx7o0** [namidaco/namida#225] opened 2024-06-13 23:56 UTC
**Is your feature request related to a problem? Please describe.**
 
I'm always frustrated when trying to start a queue in a playlist with the specific track that I desire at the time because they are in a random order. (I can't find the track i want)

**Describe the solution you'd like**

Add the option to sort tracks in playlists just like in the tracks page. (It's going to be really easy. Just copy and paste)

**Describe alternatives you've considered**

I mean, you could make manual sorting more accessible because right now, it's really hard sorting a playlist with over 15 tracks.

**Additional context**

**Apps**

I think Spotify has this, but I'm not sure.

**Comment by z9xx7o0** [comment] 2024-06-13 23:58
> 
> 
> **Is your feature request related to a problem? Please describe.**
> A clear and concise description of what the problem is. Ex. I'm always frustrated when [...] 
> I'm always frustrated when trying to start a queue in a playlist with the specific track that I desire at the time because they are in a random order. (I can't find the track i want)
> 
> **Describe the solution you'd like**
> A clear and concise description of what you want to happen.
> 
> Add the option to sort tracks in playlists just like in the tracks page. (It's going to be really easy. Just copy and paste)
> 
> **Describe alternatives you've considered**
> A clear and concise description of any alternative solutions or features you've considered
> 
> I mean, you could make manual sorting more accessible because right now, it's really hard sorting a playlist with over 15 tracks.
> 
> **Additional context**
> Add any other context or screenshots about the feature request here.
> 
> 
> **Apps**
> Add any other known apps/service that does this in a good way
> 
> I think Spotify has this, but I'm not sure.
> 

My bad, Spotify has this only in the liked songs page

**Comment by MSOB7YY** [comment] 2024-06-15 19:29
duplicate of #164
--
1. it's not in random order, its the order of insertion and u can reorder it manually 
2. implementing it is not hard, but the big issue is u gotta save the original "custom" sort to be available as a sort option too (like youtube), and currently nothing like this is saved so it will actually require more work that expected. not to mention that adding/removing will mess up the custom sort so i still gotta think about a good way to handle this
---
closing this in favor of the original issue, if u got concerns/stuff pls comment on #164

**Closed** 2024-06-15 19:30 UTC

**Comment by z9xx7o0** [comment] 2024-06-18 21:25
@MSOB7YY , issue #164 isn't the original because Issue #92 (by me) featured this request first. I also realized that i might have phrased it wrong. It doesn't really matter who is the original creator of this issue. As long as you have it in your task list.

Btw, I see this app is getting a lot of attention. And I think the reason is the YouTuber "Sam Beckman", he featured your app many times. I think about 5 times. 
I originally found out about the app from the yt channel "androinfotech." 
(I know it doesn't have anything to do with the issue, but this issue is closed. so it won't affect anything)

**Comment by MSOB7YY** [comment] 2024-06-18 21:37
@z9xx7o0 ooh i see, my bad that issue had huge list lmao.

about the app being featured yeah i saw everytime Sam featured it (the cute friends told me), that really makes me grateful. also just saw the androinfotech's one and i loved how he gave an honest review, thanks for letting me know too lmao

**Comment by MSOB7YY** [comment] 2025-01-03 11:35
this was added in v4.8.6 https://github.com/namidaco/namida/releases

> implementing it is not hard, but the big issue is u gotta save the original "custom" sort to be available as a sort option too

about this, i gave up and just show a warning that ur custom sort will be lost
