### ISSUE TITLE
[ISSUE] 

### ISSUE THREAD

**Issue by Rishabhknp666** [namidaco/namida#270] opened 2024-07-10 12:41 UTC
For new Android version a message floated saying this app does not support new version of Android  since then YouTube feature is not working for any song on YouTube
## Screenshots

Giving error

**Comment by MSOB7YY** [comment] 2024-07-12 21:55
duplicate of #265 and many others. read https://github.com/namidaco/namida/issues/265#issuecomment-2218667346

about new android versions i tried on Android 14 once before and worked fine so idk about that

**Closed by MSOB7YY** 2024-07-12 21:55 UTC
