### ISSUE TITLE
Issues/suggestions

### ISSUE THREAD

**Issue by z9xx7o0** [namidaco/namida#92] opened 2023-12-29 03:50 UTC
I have some issues i hope you can fix. 
- ~Some of the issues are in this video: https://github.com/namidaco/namida/assets/83415416/1b578461-baa6-48ee-80aa-a1576cd9bbcd~

- **~The first one is if the track is paused, I can't resume it from the notifications.~**

- The second is when I download from YouTube, it stays in ongoing. It never goes to the finished section.

- **~The third is more of a request, but anyways in most players, when you press the "previous" button, it starts the current track from the beginning. You could maybe have an option in the setting to select if it goes back to the previous track or replays the current one.~**

- **~The fourth is when the track stops playing because of an interruption, it doesn't resume by itself after the interruption is gone even though I have the setting enabled (btw the first demonstration is from YouTube music).~**

- ~Also, every time, I set the minimum track duration to restore last played position to "don't restore", when I leave the app and come back. It automatically switches to "always restore" (which i dont really want).~

- Another problem is that sometimes, when I open the app, it automatically imports old m3u files.

- Some small issues/suggestions: 
  - change acceleration when re ordering playlist/queue because it's slow (maybe make it customizable)
  - sort playlist by name, date, album, etc.
  - Delete track file from within the app
  - when changing the pitch/speed/volume, select if its for only the current song or if it stays until reset
  - make the picture of an artist a picture of them from the Web rather than an album cover
  - ~add a "play" option as one of the floating action buttons~ (long press to shuffle), 
  - add physical button controls (use volume buttons to play/pause & previous/next), 
  - ~as someone else said, pull down to refresh~
  - ~**also just a reminder when shuffling all, the current track should be at the top of the queue.**~

Sorry for the long list. This is just my opinion. Let me know if you didn't understand any.
(I bolded the most important)

**Comment by MSOB7YY** [comment] 2023-12-29 03:59
thank u so much, will look into it after.. maybe a year 😊

**Comment by z9xx7o0** [comment] 2023-12-29 06:00
If I find any additional issues/ suggestions, I will post them here (sorry for all of these, but i am using the app on a daily basis and im literally finding 2-3 bugs/issues/suggestions every day).

1. Every time I open the app I get a notification saying "namida pasted from your clipboard" even though I don't have a link copied and i didn't go to the YouTube section, (i know its because i enabled the clipboard setting but it will be better if the app only checks the clipboard when i click on the clipboard icon not every time i open the app).

**Comment by MSOB7YY** [comment] 2023-12-29 12:31
1. the message appears when copying the last text in the clipboard, it's needed to display the icon itself, and maybe in the future to display a dialog with the link to quickly download/play etc.
im not sure if monitoring should be completely disabled and the icon would be always visible

2. password protect music 😭 but i get the idea. sadly i know this can be helpful but it's so against logic, the tracks tab is meant to display ALL music on ur phone, if you want to show music except some podcasts, it might be a good idea to add that folder to "Excluded folders" in indexer settings, and then use any file manager to play with namida

also u might not know but i love suggestions, long list means more good content :>

**Comment by z9xx7o0** [comment] 2023-12-29 22:23
Issue:
If I change the pitch/speed/volume on a track, then I go to the next track. Its back to the original speed/potch/volume , so I press on the icon to change it, I see the same configuration as the one I set before, so I press done. Nothing happens. I have to interact with the sliders in order for it to  notice that i changed the pitch/speed/volume. There's that issue, and maybe add another option with the reset and done button where the user selects if they want to keep the configuration until it's changed by hand or automatically reset on the next track.

Btw you don't have to respond to every issue I post (it's like going back to school writing, writing, writing), I just want you to know it's there, so if you want, you can fix it.

**Comment by z9xx7o0** [comment] 2023-12-30 09:21
Issue/suggestion

When adding tracks to a playlist, add an indicator "added x tracks to x playlist." because I add a track to the playlist. I don't realise I added it, so I add it again. Now I have a duplicate in the playlist. Also, when adding a duplicate, it would be nice to have a "do you want to add x track again?".

**Comment by MSOB7YY** [comment] 2024-02-14 21:27
@z9xx7o0  just a reminder, most of these stuff are already done with v2.0.1, please recheck ur comments

for reference, these are done:

- [x] 1. video issues u sent
- [x] 2. resuming from notification on Android 14 is now possible
- [x] 3. previous button replays option added
- [x] 4. it will resume after interruption normally
   - after 1 second if u didnt interrupt again (cuz annoying when trying to watch some videos outside)
   - u can also specify max duration, so that if this time passed, it will no longer resume
- [x] 5. minimum track duration setting fixed
- [x] 6. "play" option as one of the floating action buttons
- [x] 7. pull to refresh
   - for tracks page
   - for playlists page & subpage (to reload m3u file/s) 
- [x] 8. shuffling all will set current track at first
- [x] 9. "namida pasted from your clipboard"
  - now will only monitor clipboard if u enabled it in settings and only when search is active
- [x] 10. pitch etc thingy is already fixed, removing volume slider seems nice but not all phones has per-app volume control so i cant really do this, u can also access these sliders within equalizer page too now
- [x] 11. adding duplicated items to a playlist will ask u for an action, and a snackbar will appear showing how many tracks are added


these are not done yet:
- [ ] 1. download from YouTube, it stays in ongoing. It never goes to the finished section
  - is this still happening? can u pls send a smol video
- [ ] 2. sometimes, when I open the app, it automatically imports old m3u files.
  - wdym by old m3u files? on each startup, it will check all existing m3u files and import them, what do u expect?
- [ ] 3. change acceleration when re ordering playlist/queue because it's slow (maybe make it customizable)
  - probably not possible idk but either ways it wont be easy
- [ ] 4. sort playlist by name, date, album, etc.
  - u can already sort by name, date and others. sorting by album is.. uh... how?
- [ ] 5. Delete track file from within the app
  - duplicate of #66
- [ ] 6. when changing the pitch/speed/volume, select if its for only the current song or if it stays until reset
- [ ] 7. make the picture of an artist a picture of them from the Web rather than an album cover
   - duplicate of #5
- [ ] 8. add physical button controls (use volume buttons to play/pause & previous/next)
  - this is already possible when the device screen is off. this should be controlled by android and not by apps, but is there any player that does this?

**Comment by MSOB7YY** [comment] 2024-05-19 18:54
yeah so most of the unfinished are non-valid/duplicates so imma close as done. as for pitch/speed/volume per track, not gonna happen ig, if it so important open a new issue

**Closed by MSOB7YY** 2024-05-19 18:54 UTC
