### ISSUE TITLE
[BUG] ... Playback error. None of any youtube video is playing.

### ISSUE THREAD

**Issue by Anshu8127** [namidaco/namida#272] opened 2024-07-11 04:55 UTC
Youtube video or music is not playing. Some popup saying 'error playing video' comes up.

## Steps to Reproduce

1.
2.
3.
4.

## Screenshots

https://github.com/namidaco/namida/assets/175281350/1fcfcce2-7ebf-4ed0-8a31-8bbb7e710be7

**Comment by MSOB7YY** [comment] 2024-07-12 21:56
duplicate of #265 and many others. read https://github.com/namidaco/namida/issues/265#issuecomment-2218667346

**Closed by MSOB7YY** 2024-07-12 21:56 UTC
