### ISSUE TITLE
[BUG]  namida app is not playing online youtube mp4 or mp3

### ISSUE THREAD

**Issue by Khan0019** [namidaco/namida#268] opened 2024-07-09 20:49 UTC
When I am trying to play a youtube video it's not playing and not even in audio. It says error playing video try again. Then it says skipping video

## Expected Behavior
 It should have play the youtube video or audio

## Steps to Reproduce

1.
2.
3.
4.

**Comment by 0dusk** [comment] 2024-07-10 08:58
Hey; that's exactly what I'm facing right now too. Let's hope developers fix this issue asap!

**Comment by Khan0019** [comment] 2024-07-10 09:08
Yep one day they will I guess and some how new version will be coming

**Comment by KumarKamble03** [comment] 2024-07-11 02:57
![Screenshot_20240711-082342_Namida](https://github.com/namidaco/namida/assets/175274784/1bc33ea4-fd9a-481b-b35a-4519469c7926)
Error while playing YouTube videos.

**Comment by CoolOmar26** [comment] 2024-07-11 05:40
Yes I have it too

**Comment by Khan0019** [comment] 2024-07-11 05:47
Now what should I do

**Comment by Khan0019** [comment] 2024-07-11 05:48
Now how should I fix it then?

**Comment by Khan0019** [comment] 2024-07-11 05:49
I don't have thread.

**Comment by krishnagupta1229** [comment] 2024-07-11 11:31
What should I do now I wanna listen to music

**Comment by MSOB7YY** [comment] 2024-07-12 21:58
@Khan0019 @0dusk @KumarKamble03 @CoolOmar26 @krishnagupta1229 duplicate of #265 and many others. read https://github.com/namidaco/namida/issues/265#issuecomment-2218667346
to make it clear youtube recently broke existing clients that depend on web client. everything is working fine in beta

**Closed by MSOB7YY** 2024-07-12 21:58 UTC

**Comment by murmuvikash** [comment] 2024-07-13 11:34
Me too

**Comment by Here4atharvvv** [comment] 2024-07-16 19:56
> @Khan0019 @0dusk @KumarKamble03 @CoolOmar26 @krishnagupta1229 duplicate of #265 and many others. read https://github.com/namidaco/namida/issues/265#issuecomment-2218667346
> to make it clear youtube recently broke existing clients that depend on web client. everything is working fine in beta

When it will fix?

**Comment by MSOB7YY** [comment] 2024-07-17 11:17
@Here4atharvvv fixed in beta? wait the new release for stable

**Comment by youbitchy00** [comment] 2025-01-22 20:17
Can anyone tell me how to fix this issue?🙏 I'm so saddd cause I can't play or download any video.. please 😭😭😭😭😭

**Comment by FastCocobo** [comment] 2025-01-22 20:29
@ybitchy00 What version are you on?

**Comment by youbitchy00** [comment] 2025-01-23 01:29
> [@youbitchy00](https://github.com/youbitchy00) What version are you on
It's v.4.9.2 - beta.

**Comment by MSOB7YY** [comment] 2025-01-25 00:27
fixed in **v4.9.4** https://github.com/namidaco/namida-snapshots/releases

**Comment by youbitchy00** [comment] 2025-01-25 08:47
> fixed in **v4.9.4** https://github.com/namidaco/namida-snapshots/releases

THANK YOU SO MUCH FOR HELPING ME OUTT!!!!😭. YOU'RE SO COOL💗💗💗

**Comment by MSOB7YY** [comment] 2025-01-25 10:25
and you are varry cute❣️❣️
