### ISSUE TITLE
[BUGS] bugs relating to embedded lyrics.

### ISSUE THREAD

**Issue by z9xx7o0** [namidaco/namida#132] opened 2024-02-21 18:53 UTC
1. the auto scroll is a little unpredictable, sometimes it works perfectly, sometimes it shifts the lyrics up a little, and sometimes it shifts the lyrics up so much that it's out of the frame so it unreadable and everytime I scroll down it re shifts the lyrics to the same position. I'm not sure, but I might have a little idea of why this might be happening, I noticed that sometimes, when a lyric section is multiple lines, it shifts it up but when it is a single line it is in the middle. So maybe because it's multiple lines, it treats it as multiple lyric sections and shifts it up more than it is supposed to? As I said, I'm not sure, but this is kind of what I'm encountering.

2. When editing bottom line lyrics, the keyboard covers the place I want to edit, and I can't see it.

3. When I'm editing a line and want to switch to another line, the lines Inbetween are selected.

4. If I edit the lyrics or tags outside the app, the app doesn't register it even if I refresh, so I think I have to re index everything (which i don't want to do for only 1 track)
Instead, I edited the tags (in Namida), which I mean by deleting a single character, saving, then re adding that character and saving.

**Comment by MSOB7YY** [comment] 2024-02-21 21:14
i encountered the first bug some times, its quite random and i dont think its because as what u said, i still have to investigate more

about editing tags outside namida, why not do a track re-index in track advanced dialog? thats what its made for

**Comment by z9xx7o0** [comment] 2024-02-21 21:45
Well, something important to note about the first one is that some tracks are always centered, and some tracks are always offset no matter how many times I replay them.

**Comment by MSOB7YY** [comment] 2024-04-27 21:24
points 2, 3 & 4 were fixed in db055a403406454bca690daf2259e38e21ba5d99.
going to close in favor of #123, since point 1 is a duplicate of it

**Closed by MSOB7YY** 2024-04-27 21:24 UTC
