### ISSUE TITLE
Features requests/ bug in the latest app version 

### ISSUE THREAD

**Issue by hibonox705** [namidaco/namida#21] opened 2023-10-14 20:38 UTC
Hi,

First of all love your app, it's really nice to have a new looking music and video app.
I don't know how hard it's to code it but i have different request and bugs to report.
#### ~Third one is that in the indexer section,  album identifiers. We can't select and save anything but the already pre-selected Name setting.~

------
UPDATE:
with [v1.4.8](https://github.com/namidaco/namida/releases/tag/v1.4.8), issue is partially resolved

- [ ] Album Artists tab, along with search
- [x]  subpages tracks sorting (b82dce29d98b01f69fba1ea44bee7e131dd44a41) (available since v1.5.4)
- [x] album tracks sorting fix
- [x] album identifiers saving in settings

**Comment by MSOB7YY** [comment] 2023-10-15 00:11
thank you so much, im glad u like my app
 now for ur requests
1. i don't quite get what is the expected behavior, are u talking about the sort or the mini search filter? sorting & search filter both works as intended
   - featured artists appearing as a separate entry is actually a feature for a more organized library, yet u can still disable from indexer "Extract feat. artists"
 2. previously album tracks were sorted by year or title, i didnt know ppl want their albums to be sorted normally 😶‍🌫️ next release has a fix for this, while exposing all searching alternatives are also requested, i might get working on it sooner
 3. how come? the name is forcely enabled, while u get `year` and `album artist` as extra, do you mean u can't select those 2? can u send a video please?

**Comment by PlumBlossoms13** [comment] 2023-10-15 01:35
For point three, you can select 'year' and 'album artist' just fine but the save button doesn't work.

**Comment by Red6785** [comment] 2023-10-15 02:06
You are on v.1.3.0? I had that problem back on 1.0.0, but updating fixed it.

**Comment by MSOB7YY** [comment] 2023-10-15 02:08
oh ops, a fix has been pushed 1bcee8b12907f5da036bd71164a8dea8849e15ea
apparently i was only activating it if the values are not the same 
https://github.com/namidaco/namida/blob/a3dcedcc1134ef3aa6c7ba28b6b92d5c7696ffa2/lib/ui/widgets/settings/indexer_settings.dart#L229

**Comment by hibonox705** [comment] 2023-10-15 20:38
> thank you so much, im glad u like my app now for ur requests
> 
> 1. i don't quite get what is the expected behavior, are u talking about the sort or the mini search filter? sorting & search filter both works as intended
>    
>    * featured artists appearing as a separate entry is actually a feature for a more organized library, yet u can still disable from indexer "Extract feat. artists"
> 2. previously album tracks were sorted by year or title, i didnt know ppl want their albums to be sorted normally 😶‍🌫️ next release has a fix for this, while exposing all searching alternatives are also requested, i might get working on it sooner
> 3. how come? the name is forcely enabled, while u get `year` and `album artist` as extra, do you mean u can't select those 2? can u send a video please?

No problem, thank you for developing such an app

Basically I'm comparing it to other music app where album artist show the artists that you have albums and singles from them. The original artist that released it

And no problem for the other suggestions I will wait for the update when it comes out

**Comment by MSOB7YY** [comment] 2023-10-15 20:52
i think i got what u want now

currently the library is organized by every artist, would your issue get resolved by adding a separate `Album Artists` tab ? 

-----
also thanks, the new version is going to be published tomorrow

**Comment by hibonox705** [comment] 2023-10-15 21:19
> i think i got what u want now
> 
> currently the library is organized by every artist, would your issue get resolved by adding a separate `Album Artists` tab ?
> 
> also thanks, the new version is going to be published tomorrow

Yes if possible of course

Oh nice can't wait to have a look at it

**Comment by MSOB7YY** [comment] 2023-10-16 18:52
with [v1.4.8](https://github.com/namidaco/namida/releases/tag/v1.4.8), issue is partially resolved

- [ ] Album Artists tab, along with search
- [ ]  subpages tracks sorting
- [x] album tracks sorting fix
- [x] album identifiers saving in settings

**Comment by hibonox705** [comment] 2023-10-16 19:03
> with [v1.4.8](https://github.com/namidaco/namida/releases/tag/v1.4.8), issue is partially resolved
> 
> * [ ]  Album Artists tab, along with search
> * [ ]   subpages tracks sorting
> * [x]  album tracks sorting fix
> * [x]  album identifiers saving in settings

Yeah just saw the update thanks for doing so.
And for the rest no problem don't rush, take your time. It's already mind blowing having a music player like this on GitHub, so no rush for the rest. Take your time and take time for yourself don't burn yourself out

**Comment by MSOB7YY** [comment] 2023-10-16 19:25
thank u so much really, i do this because i love it so dw, ty 🌺

**Closed** 2024-04-07 14:26 UTC

**Comment by MSOB7YY** [comment] 2024-04-07 14:28
as mentioned, Album Artists and Composers are now available as a dropdown button in artists page, this one took a while ty for being patient

**Comment by hibonox705** [comment] 2024-04-07 16:33
Let's go, thanks for taking time to develop it and implementing it.
Just updated the app and it works flawlessly 👌
