### ISSUE TITLE
[FEATURE REQUEST] Album Art placement in large screen devices..

### ISSUE THREAD

**Issue by Mathew20kdroid** [namidaco/namida#428] opened 2024-12-16 14:44 UTC
As of now I'm using the latest beta 4.8.1
The "**album art**" on large screen devices on the now playing sceen is on the "**left side**" as of now....
1. It would be nice if the album art is positioned in the "middle"...
2. I would prefer something like insted of aligning the album art to the middle, "**the titile and some other info**" can be showed on the right side....it would make sense as to being a proper tablet or large sceen layout for the now playing screen
"It can even switch between the **song info** and the **lyrics** as well"

![Screenshot_20241216_141320](https://github.com/user-attachments/assets/5f5074c9-a16a-40fb-81b7-7165d33c22f4)

![Screenshot_20241216_141320](https://github.com/user-attachments/assets/4377d396-0afe-4a48-9d9a-628f62d4a89c)

**Comment by MSOB7YY** [comment] 2024-12-22 19:33
it wasnt intentionally made this way, this was just a workaround for image overflowing the whole screen when the screen is more like a square.

there is a request for supporting wider displays (#142), the miniplayer is hard to play with but i lowkey planning to redesign it for large screen (queue on the right etc)

this issue is duplicate of (#202), there is exact request

> "It can even switch between the song info and the lyrics as well"

use the second button on bottom right? and to enter lyrics fullscreen u can long press the lyrics view

**Closed** 2024-12-22 19:33 UTC
Labels: feature request
