### ISSUE TITLE
[ISSUE] 
Player after some time stops in background (logs in mail)

### ISSUE THREAD

**Issue by soechka12** [namidaco/namida#366] opened 2024-10-08 17:38 UTC

**Comment by MSOB7YY** [comment] 2024-10-15 01:45
hey the logs say nothing really, are you sure u using the arm64 version? u may try beta too https://github.com/namidaco/namida-snapshots/releases

bothways this is duplicate of #184

**Closed by MSOB7YY** 2024-10-15 01:45 UTC
