### ISSUE TITLE
[QUESTION] Moving Songs Re-Index

### ISSUE THREAD

**Issue by PlumBlossoms13** [namidaco/namida#134] opened 2024-02-24 11:25 UTC
Hello again!

I'm moving a some of my songs from the internal storage of my phone to an SD card, that's included in my list of folders for the music library

When I update the directory path, I noticed that it doesn't update in the pop-up box and re-indexing that particular album doesn't fix it. However, the songs are found again and play normally after I re-index my *entire* library (though the little heart is reset nbd). Is that intended?

**Comment by MSOB7YY** [comment] 2024-02-24 21:57
hello, updating directory path is only meant to update the paths reference inside history, playlists, favorites, queues, etc. totally different from re-indexing.

selecting tracks/album etc and reindexing it only, means refreshing the metadata obtained during first indexing, it will fail if the real path is no longer found 

so yah it's intended, in ur case u would have to:
1. move ur music
2. update indexer folders (if necessary)
3. re-index/refresh to update library
4. "update directory path" to update lost path references in various namida parts

**Comment by PlumBlossoms13** [comment] 2024-02-25 02:59
Ah, got it! Thank you! 🤗

**Comment by PlumBlossoms13** [comment] 2024-02-29 10:17
I've followed the steps you gave me but my library still seems to be broken and I can't figure out why. I had my song files on both my phone and an SD card and have moved all the files to a new, larger SD card. I tried the last step in the advanced settings but all of my play counts and favorites are gone

Sent from Yahoo Mail on Android 
 
  On Sat, Feb 24, 2024 at 4:58 PM, ***@***.***> wrote:   


hello, updating directory path is only meant to update the paths reference inside history, playlists, favorites, queues, etc. totally different from re-indexing.

selecting tracks/album etc and reindexing it only, means refreshing the metadata obtained during first indexing, it will fail if the real path is no longer found

so yah it's intended, in ur case u would have to:
   
   - move ur music
   - update indexer folders (if necessary)
   - re-index/refresh to update library
   - "update directory path" to update lost path references in various namida parts

**Comment by PlumBlossoms13** [comment] 2024-03-01 17:10
![Screenshot_20240301-120859](https://github.com/namidaco/namida/assets/109384939/83f2ced4-48ea-4194-9e07-dc5fb20283f5)

**Comment by MSOB7YY** [comment] 2024-03-01 17:19
@PlumBlossoms13 quite interesting, what exactly do u type when updating directory path? i have did this million times without issues, if u got duplicates then just do a refresh/reindex afterwards

**Comment by PlumBlossoms13** [comment] 2024-03-01 18:07
In the directory path, I put in the new directory path on the SD card (/storage/0123-4567/Music). I've copy-pasted and typed it out just in case that might have an effect but it was the same either way.

That was my first thought but, for some reason, the new, duplicated track disappeared too even though I have the new music folder in the list

My friend moved his library without issues as well and I did the same thing as him so it is pretty weird

**Comment by MSOB7YY** [comment] 2024-03-01 21:21
yeah thats the new path, what about the old one? what do you type exactly?

**Comment by PlumBlossoms13** [comment] 2024-03-01 22:17
For the old path I typed either "/storage/emulated/0/Music/Songs" or "/storage/D0F6-4C1C/Music" depending on where my music was on my phone

**Comment by PlumBlossoms13** [comment] 2024-03-03 03:44
Sorry to keep bothering you, I'm trying to figure this out on my own because you might be busy. 

I've looked through my Playlist tab and noticed that some of the songs from my old "/storage/D0F6-4C1C/Music" directory actually work fine and the play counts are still there _but_ the heart is gone. The ones from that directory that don't have the new path still have their heart. I'm not sure why some have the updated path and lost their heart while some didn't update at all. Everything from "/storage/emulated/0/Music/Songs" is still broken along with my playlists and my Favorites list that, oddly, still have the hearts from songs that lost them in the Track tab

**Comment by MSOB7YY** [comment] 2024-03-03 06:34
@PlumBlossoms13 ur not bothering dw i just don't have a complete image about what's going on wrong.

just notice that favourites is also a playlist saved by path too, if u moved a track, it means it will no longer be in favorite playlist

alr so what i get is:
  1. ur favorite playlist & other playlists still have the old paths
  2. history also still has old paths, am i right?
 
have you tried pressing on any track that is lost (a track u moved) and choose advanced from dialog > update directory path, then check if it was properly updated? would be better if u video recorded it too.
if it worked then proceed with the old way (from settings page) and see

**Comment by PlumBlossoms13** [comment] 2024-03-03 07:20
The history list still have the old path and so do my playlists. The favorite playlist isn't one I made, it's the one in the playlist tab at the top

If I press a track and go through the advanced dialogue about updating the path, it works and restores everything. Doing it from the advanced settings doesn't update the paths

https://github.com/namidaco/namida/assets/109384939/ca253431-658e-48cf-b665-1e7ac2a518d0

I think this video shows everything you might need but let me know!

**Comment by MSOB7YY** [comment] 2024-03-03 08:36
@PlumBlossoms13 yeah uh.. have u tried to restart app? like force stopping
also u may check disabling "update missing tracks only" (if you moved everything in the folder)

this really is weird but i remember having a similar issue and just restarted
lemme know

**Comment by PlumBlossoms13** [comment] 2024-03-03 18:15
I've tried restarting and clearing the cache a few times but it stays the same along with disabling "updating missing tracks only"

**Comment by MSOB7YY** [comment] 2024-03-03 20:26
@PlumBlossoms13 ughhh.. can you please backup your history+playlists+database+queues and send me the file (here or in telegram/discord), i will try to update paths myself

**Comment by PlumBlossoms13** [comment] 2024-03-05 00:25
@MSOB7YY sure I can do that! I don't have 

[Namida Backup - 2024-03-04 07.24.03.zip](https://github.com/namidaco/namida/files/14488664/Namida.Backup.-.2024-03-04.07.24.03.zip)

**Comment by MSOB7YY** [comment] 2024-03-05 23:54
i can confirm this has an issue, the only place where it gets updated is queues. while history/playlists/favs are not updated, gonna see whats going wrong

**Comment by PlumBlossoms13** [comment] 2024-03-06 00:54
Okay! There's no rush so please take your time! Thanks for all your help so far! ❤️

**Comment by MSOB7YY** [comment] 2024-03-18 16:57
@PlumBlossoms13 sorry i forgot to give updates, so the updating actually worked fine, but i had to disable "update missing tracks only", this option actually checks if the new file exists before replacing.
if this still didnt work for you, the new "missing tracks page" in next update should help a bit

also can u try the latest build from here?
leaving open till we see results.

**Comment by PlumBlossoms13** [comment] 2024-03-18 23:55
No problem!
Disabling the "update missing tracks didn't change anything" like before

For the latest build, what exactly should I be looking for? It installed as a new app

**Comment by MSOB7YY** [comment] 2024-03-19 02:35
@PlumBlossoms13 yep u import ur backup and try to update directory path from there. lemme know the results

**Comment by PlumBlossoms13** [comment] 2024-03-19 02:53
Okay updating the directory didn't work. The new missing track option did but it seems like it only worked for the History and Most Played lists. Favorites still has the old path

**Comment by MSOB7YY** [comment] 2024-04-23 10:50
@PlumBlossoms13 thanks for the "no rush" i really wish i can make things go as intended but it's hard without being able to reproduce. as for the stuck issue, how many tracks+history+playlists tracks have you got? it might take longer if u have many, but steps 2-5 shouldn't take so long. can u also provide logs? might be a bug that throws without being handled

**Comment by MSOB7YY** [comment] 2024-04-23 10:54
update: i checked and it throws at some point, gonna check and fix sorry for that

**Comment by PlumBlossoms13** [comment] 2024-04-25 05:45
@MSOB7YY You're welcome ❤️ I have about 2300 tracks but some of them I've added recently. I thought that the amount of tracks I have would be a factor but I let it go for like 15 minutes so I wasn't sure just how long I should wait 😅

No need for sorry, take your time! ❤️

**Comment by MSOB7YY** [comment] 2024-04-25 10:44
yeah that shouldn't take much time at all, probably only few seconds. the issue happens cuz somehow preparing m3u playlists is called, so i should fix that

**Comment by MSOB7YY** [comment] 2024-04-27 21:31
@PlumBlossoms13 yo can u try the one here? https://github.com/namidaco/namida/actions/runs/8862663911

(if your using stable version, u can just import a backup from it then test)

**Comment by PlumBlossoms13** [comment] 2024-04-28 03:42
@MSOB7YY This worked! My Favorites list still looks like this but this happened before so I can wait until you have the time to look into it. Thank you! ❤️
![Screenshot_20240427-234207](https://github.com/namidaco/namida/assets/109384939/d59ee0cb-319c-43ea-af15-f39da6c74282)

**Comment by MSOB7YY** [comment] 2024-04-28 11:52
yep at least all others are working and the issue is only with favourites, gonna have a look into it

**Comment by MSOB7YY** [comment] 2024-05-19 18:47
yo i did some changes to the internal playlist manager, i tested again and it worked as intented so this should be fixed. u can try the [beta](https://github.com/namidaco/namida-snapshots/releases/) build or wait the stable release. bothways its working as it should be so im not sure if u still got the same issue

**Closed** 2024-05-19 18:47 UTC

**Comment by PlumBlossoms13** [comment] 2024-05-19 21:22
@MSOB7YY I just tried the new beta build you linked! Everything worked like the last build I tested except for the Favorites Tab still 😔

**Comment by MSOB7YY** [comment] 2024-05-19 21:26
@PlumBlossoms13 bruh i have nothing more to investigate in. just send me ur favorite list (from backup) again and i will update it for you

**Comment by PlumBlossoms13** [comment] 2024-05-20 10:20
Here's the json file but let me know if you need the whole backup archive. The first two songs have the right path but those are the ones I did individually to see if it would work

[favs.json](https://github.com/namidaco/namida/files/15375853/favs.json)

**Comment by MSOB7YY** [comment] 2024-05-20 11:31
@PlumBlossoms13 so u basically want to change all "/storage/emulated/0/" to "/storage/0123-4567/" right?

**Comment by PlumBlossoms13** [comment] 2024-05-20 16:07
Yeah that's the new directory! Also "/storage/D0F6-4C1C/Music" if that's still showing too

(But, if all that needs to be done is editing the file like a text file, I could do that on my own if you'd like. I didn't think it could be something so simple 😅)

**Comment by PlumBlossoms13** [comment] 2024-05-22 18:51
@MSOB7YY YOOO I FIXED IT (Sorry for yelling 😂)

Anyway, I updated to the stable version today and did the missing tracks process and noticed that it went history -> library -> playlist track. I thought maybe it wasn't looking at the Favourites that Namida already makes when you favorite a song so I made a playlist called Favourites and put those songs there, did the missing tracks thing and it fixed it! All the storage paths in the automatic favourites playlist are right and the tracks play and everything!

**Comment by MSOB7YY** [comment] 2024-05-22 19:26
@PlumBlossoms13 YOOOO yo frr? lmaoo i already did update it from a clone version but needed to know exact new path for each folder lmao

wdym deleting custom-favourite playlist removed the hearts? the only way is to actually press the heart yourself or select tracks and remove, u cannot delete the default favourite playlist.


as i said i already updated so its working fine (i disabled check "update missing tracks only") so if it still not working for u, then i gotta suggest:
1. select all tracks in favourite playlist
2. add to custom playlist (any name)
3. settings -> advanced -> update directory path
4. after updating, go the custom playlist, select all, open dialog, add to playlist, (and with the new option) u can add all to default favourite playlist. done

**Comment by PlumBlossoms13** [comment] 2024-05-22 19:42
I'm not sure how it happened tbh lol. But when I deleted my Favourites that I made myself and then deleted it when everything was fixed, all the hearts were gone everywhere else and the default favourite list was empty. I can screen record if you wanna see since it doesn't take long to fix again

I'm kinda lost with the steps, sorry, because what should I update the directory path to when it's already correct?

**Comment by MSOB7YY** [comment] 2024-05-22 19:48
its already correct like no more issues? if thats the case then ur all good lmao
otherwise send me screen record or something to grasp the situation better

**Comment by PlumBlossoms13** [comment] 2024-05-22 19:50
Yeah everything's good now! Thank you sooo much for all your help and patience really ❤️ I'll leave a review on the discord channel when I get home from work! 💕

**Comment by MSOB7YY** [comment] 2024-05-22 20:12
ahhh finally man that took quite a long run lmaoo, thank you for being patient not me and no need for review lmao just hope u do good in ur job 💗 thank u sm 💝
