### ISSUE TITLE
[ISSUE] Can't organise songs in playlist, like sorting by name, time, date added or date modified 

### ISSUE THREAD

**Issue by Lyondave** [namidaco/namida#322] opened 2024-08-10 17:12 UTC

**Comment by MSOB7YY** [comment] 2024-08-10 18:40
duplicate of #164

**Closed by MSOB7YY** 2024-08-10 18:40 UTC

**Comment by MSOB7YY** [comment] 2025-01-03 11:33
this was added in v4.8.6 https://github.com/namidaco/namida/releases
