### ISSUE TITLE
[BUG] Unsupported font in lyrics.

### ISSUE THREAD

**Issue by Not-James-Bond** [namidaco/namida#188] opened 2024-05-11 22:10 UTC
Some LRC lyrics shows some kind of gibberish text (Usually in Hindi songs) 
## Expected Behavior

Supported readable lyrics should be visible.
## Current Behavior

Unsupported font was being shown for few songs. 
## Steps to Reproduce

1. Open Namida.
2. Play music "Khudi by Local Train"
3. Open Lyrics.
4. Unsupported font will be shown.

## Screenshots

![Screenshot_20240512-033358](https://github.com/namidaco/namida/assets/32868290/c22ab21a-5dfd-4104-82d7-0aa2cbd41523)
![Screenshot_20240512-033146](https://github.com/namidaco/namida/assets/32868290/86e01069-3f87-43f3-8246-f79721d0bec2)

**Comment by MSOB7YY** [comment] 2024-05-11 22:16
this was a font issue and was fixed in an earlier commit. wait the new release or use beta version from github action tab.

bothways this duplicate of https://github.com/namidaco/namida/issues/183

**Comment by Not-James-Bond** [comment] 2024-05-12 07:24
> this was a font issue and was fixed in an earlier commit. wait the new release or use beta version from github action tab.
> 
> bothways this duplicate of #183

Used latest build from GitHub action workflow: https://github.com/namidaco/namida/actions/runs/9037354238

Still same lyrics issue.
![Screenshot_20240512-125343](https://github.com/namidaco/namida/assets/32868290/d0b95b5b-c139-421d-a507-3c15b15788af)
![Screenshot_20240512-125401_Namida](https://github.com/namidaco/namida/assets/32868290/8b5582c3-7c25-4399-8bd1-e70733428bb2)

.

**Comment by MSOB7YY** [comment] 2024-05-12 16:12
😦😦 opss

**Comment by Not-James-Bond** [comment] 2024-05-13 07:24
It seems on few lyrics it's working but on others it's not.

**Comment by MSOB7YY** [comment] 2024-05-14 18:10
@Not-James-Bond lyrics issues are all fixed now, gonna push soon and then u may use beta or wait the stable release in a week

**Comment by Not-James-Bond** [comment] 2024-05-14 18:22
@MSOB7YY I'll test out the beta and probably will switch to stable later. Thanks. Mind Sharing the PR as well? I'd like to see the changes.

**Comment by MSOB7YY** [comment] 2024-05-14 21:28
@Not-James-Bond yeah i just pushed, the fix is done in 47c2351fd76ed7f0cb8153f00536082507b9c019 (was due to default parsing behavior that supposes everything is latin)

other lyrics improvements can be seen for example in bb27bf384003e2c09d24fff0693d4e277a7892c7, 060ccef271b96ab9ce71fb6e0397e01efa2a4b54, 7a63a6e26e68028fa909da9e76d1e5f538c95f4a, f59f23f3325cdc02ab8fecc42a8efb43ba73f75b, 9eecbcb323b9c7b6692a75592dcf86dd1ed6b4eb & dynamic lyrics feature in 8426584fc5d1d21d33a8c8384353fe8c8cbd78bd

**Closed** 2024-05-14 21:28 UTC
