### ISSUE TITLE
Change app icon to matrial you [FEATURE REQUEST] 

### ISSUE THREAD

**Issue by Singout69** [namidaco/namida#230] opened 2024-06-20 02:59 UTC
Namida Music Player is great, but its app icon feels a bit old. Since most Android apps now use the Material You theme, it would be awesome if the Namida icon could get an update to match.

**Comment by MSOB7YY** [comment] 2024-06-20 22:49
sure, just if you were to design it and let us use it ^^ duplicate of #220 tho

**Closed by MSOB7YY** 2024-06-20 22:49 UTC
