### ISSUE TITLE
[Bug] Deleting Cached Lyrics

### ISSUE THREAD

**Issue by PlumBlossoms13** [namidaco/namida#64] opened 2023-11-16 02:09 UTC
Rarely, I'll have a song that fetches the wrong synced lyrics (not sure how this process really works, sorry). It's not a problem for me since I have the plain lyrics embedded. But, when I go to delete the cached lyrics so the player will display the embedded lyrics, the wrong ones are still there because the save button doesn't work after deleting the cached ones
![Screenshot_20231115-210611-397](https://github.com/namidaco/namida/assets/109384939/ca9cba3f-2da1-4eff-aec7-0155b34c55dd)

**Comment by MSOB7YY** [comment] 2023-11-16 02:40
this isnt a bug really
- the save button will only work if the choosen lyrics is NOT in app cache, (i.e. disabled button == no need to save cuz it will already get picked)
- deleting a lyrics doesn't require saving, it instantly deletes the file in cache
- if you would like ur embedded lyrics to be prioritized, please make sure its enabled in `extra settings`, this should fix ur issue
![image](https://github.com/namidaco/namida/assets/85245079/1aab5e41-5663-401e-a8c8-c2a88c3ec90f)

**Comment by PlumBlossoms13** [comment] 2023-11-16 04:34
I thought about the embedded lyrics setting, actually! But I like having the app fetch synced lyrics and this is the only song that fetches the wrong lyrics so I think I can embed the synced lyrics in this one song instead. But thank you for the quick response!

**Comment by MSOB7YY** [comment] 2023-11-18 16:27
1. yeah that should be the solution, having a specific choice for each track is a pain for implementation and pain for the user
   - u might also put ur own .lrc (not embed), this will be used instead of the cached version, which will be a better solution
2. yes it does lmao, u just need to refresh the track since u edited it outside, just select the edited tracks > open track menu > advanced > re-index
3. might be an issue with the fetched file itself, would be glad if u provided it here (the fetched file if u can access it, or a screenshot after long pressing lyrics button)

**Comment by PlumBlossoms13** [comment] 2023-11-21 08:57
Sorry for the late reply but I've got it working now! The main issue was that the song is a different language version of the same group's song with the same name. I'm not sure where the lyrics are fetched from so I wanted to bring this to your attention
Thanks for your time!

**Comment by MSOB7YY** [comment] 2023-11-21 16:50
oh i see now, that's because lyrics are saved by filename of the music file, same filename should mean same music and that's why.

also lyrics are fetched from [lrclib.net](https://lrclib.net) (synced/unsynced) or from google (unsynced)

again, if there is any issue with the fetched lyrics, one can always
  1. put their own (add lyrics file) to be used instead of the cached one
  2. embed lyrics (by editing tags) and enable (priorities embedded lyrics)

i think the issue is done now, sorry for late reply firstly,  i will close the issue, pls reopen if there is any more issue

**Closed by MSOB7YY** 2023-11-21 16:50 UTC
