### ISSUE TITLE
[FEATURE REQUEST]  Namida for Android TV

### ISSUE THREAD

**Issue by NerdOOLV999** [namidaco/namida#309] opened 2024-08-04 16:52 UTC
I really like the UI in mobile could please make version for Android TV

**Comment by MSOB7YY** [comment] 2024-08-05 10:47
the app should work normally on android tv.. doesn't it?
if it does normally then this issue is a duplicate of #202 which requires proper ui scaling etc

**Closed** 2024-10-03 15:24 UTC
Labels: closing soon
