### ISSUE TITLE
[FEATURE REQUEST] Fetching Album Images from Last.fm & More.

### ISSUE THREAD

**Issue by 1YuvrajS** [namidaco/namida#111] opened 2024-01-14 13:21 UTC
- [x] 1. Allow useres to download and Embed Album Arts to the Batch ( Whole Album ) and one by one ( Single Track ) with the help of Last.fm.

- [x] 2. Allow useres to delete the Track within Namida app without going to the File Manager.

- [x] 3. Update Recently Added every time when new Download Songs can be appeared in it.

- [x] 4. When I move Song to another Sub Folder in the Download folder or another in Phone Directory ( Download folder existed by Default in Namida ) shows me dialogue Deleted/Moved/Modified etc.

- [x] 5. Why I have to re-index the Album by going to by holding long touch to Open Context Menu > Advanced > Re-index with Artwork Ticked. Can you give reasons?

- [x] 6. Update Album info online button that users can update Metadata of Album to get correct info ( User can select desired 1 info rest of 6 so on ) or cancel it.

**Comment by MSOB7YY** [comment] 2024-01-30 17:32
1. duplicate of #5
2. duplicate of #66
3. this means auto refreshing, currently i don't want this, i have stated this many times before that this is mainly to prevent unwanted tracks removal, but i think its a good idea to only add tracks when refreshing and that can be automatic.
4. that's because u moved it?? sadly we are not using any magic to auto point to the new location so u should update this manually, u should find suggestions if u refreshed ur library, otherwise u would have to choose the file. (related #117)
5. that's only in case u edited the tags outside and just want to refresh then in namida, similar to normal re-index but for some tracks only.
6. also related to #5

**Closed** 2024-01-30 17:33 UTC
