### ISSUE TITLE
[ISSUE] Poor scaling on foldables phones

### ISSUE THREAD

**Issue by AltRetroDood** [namidaco/namida#275] opened 2024-07-11 21:36 UTC
Idk if this counts as a issue or bug, but basically the scaling isn't great when using the inside screen. the grids in the album tab are messed up and the cover image is too big in the player screen. some tabs look really good though (like the home tab)

ALSO you don't need to prioritize this kind of issue since there are probably not that many foldable phones users anyways but I just wanted to spread awareness I guess

## Expected Behavior

not sure how the UI can be changed for it to work properly but maybe having it look similar to the landscape view on Samsung Music

## Screenshots

IMGUR link : https://imgur.com/a/O9r7P9q

## Logs

[logs_2.0.6_240409151.txt](https://github.com/user-attachments/files/16183724/logs_2.0.6_240409151.txt)

## Possible Solution

having the ability to have separate scaling options or grid numbers on for each screen

**Comment by MSOB7YY** [comment] 2024-07-12 22:03
really duplicate of #202. namida is not designed for landscape tbh and not really a priority so this might take longer. sorry for that
BTW, u can change grid size from 1 to 4 in almost each screen (literally the grid icon top right)

thanks for the imgur explanation tho, made me realize how ugly namida can look lmao

**Closed by MSOB7YY** 2024-07-12 22:03 UTC

**Comment by MSOB7YY** [comment] 2024-07-12 22:04
whats the sauce for these
![Screenshot_20240713-000347_Brave](https://github.com/user-attachments/assets/293f24e5-6045-43fe-abe8-911c2b7d0bcc)
