### ISSUE TITLE
[BUG] Songs disappear when swiping them away in the queue

### ISSUE THREAD

**Issue by ZSabiudj** [namidaco/namida#256] opened 2024-07-05 12:41 UTC
When swiping away a song in the Queue, it doesn't render properly 

## Expected Behavior
Render the track in the queue

## Current Behavior
After deleting a track in the queue by swiping a black bar get shown at it's place and the other songs wont render on top of that.

## Steps to Reproduce
1. Go to the Queue
2. swipe away an item
3. black bar appears
4. Scroll away from and back to it to fix it

## Screenshots

https://github.com/namidaco/namida/assets/89997998/baef83ac-562a-40a4-a7a4-caf9d950690b

## Possible Solution

Render the tracks on top of everything except the menu bars maybe?

**Comment by MSOB7YY** [comment] 2024-07-05 16:30
duplicate of #219 and was fixed in beta, use it or wait the next release 

*quite the pfp tho*

**Closed by MSOB7YY** 2024-07-05 16:30 UTC

**Comment by ZSabiudj** [comment] 2024-07-06 06:38
Couldnt find an entry like this, sorry for the inconvenience, 
but just wanted to say i *really* like this project :3
