### ISSUE TITLE
[FEATURE REQUEST] 5 requests

### ISSUE THREAD

**Issue by Prokilo1987** [namidaco/namida#239] opened 2024-06-26 00:15 UTC
Hello namida team,

I want to say that your app is amazing and has real potential, this mail is just a few ideas to improve the app:

1 - synchronise app with Musicbrainz (its open source as well as their thumbnail database) this way the app can download thumbnails and rectify tags just like Power amp does, could be even better if you can use multiple data bases (spotify / apple music / sound cloud / music brainz / google) 

2 - add possibility to drag the scrolling cursor and slide it up and down when navigating library

3 - when listing by title add alphabetic characters on the side so we can go directly to the wanted character

4 - add possibility to add favorites to the library tabs (directly not just in playlists menu) 

5 - add possibility to navigate library by just seeing thumbnails where they would be 3 or 5 thumbnails in each line (3 rows x Nb of lines) 

I want to say that your app made me no longer a Poweramp user, I'm very inspired by your work and hope to see your app reach its true potential, I hope my ideas will be taken seriously, especially the thumbnails idea.

**Comment by MSOB7YY** [comment] 2024-06-27 16:25
first thank u so so much, glad u like it ^^
about ur requests 
1. thats already planned but later, also a duplicate of #5
2. u can already do that lmao
3. i tried working on this before, yeah was good and all but kinda pointless, giving how namida allows showing/hiding any info on the track tile. might rethink about this later.
4. i don't think it's a good idea, favorites are literally a playlist
5. sorry i don't get this one, what do u mean by "just seeing the thumbnail" ? and what lines like which part of the app u talking about?

thank u again really, so grateful that ppl like u finding it useful ^^

**Comment by l300lvl** [comment] 2024-06-30 00:03
1: I hope Discogs, far more logical and complete than some of those "other" dbs...js.

5: op means do not display any text on album tile so something like

settings>customizations>album tile>display album art only/no artist/track/number/information

**Comment by MSOB7YY** [comment] 2024-06-30 00:17
5. in that case he can already do this in `settings>customizations>album tile`
   - top right date > disable
   - track number in album page > disable
   
 @Prokilo1987 u can also just toggle the "grid" button in album/artist/genre/playlist pages, it will display 1 tile or 2, 3, 4 grids

**Comment by l300lvl** [comment] 2024-06-30 00:28
those methods still seem to display some text like the artist, I think they want to view only artwork. Unless I've missed something

**Comment by Prokilo1987** [comment] 2024-09-20 17:33
Hi, will ever get widgets for namida? Just a simple widget will do for fast
access simply

**Comment by MSOB7YY** [comment] 2024-09-20 18:52
its requested at #168, sadly its quite complicated at the moment so im not sure this will come any near or not.

alternatively third party widget packs are working fine, they require the app to be active tho

**Comment by Prokilo1987** [comment] 2024-09-20 19:52
Understood thank you regardless

**Comment by Prokilo1987** [comment] 2024-09-20 20:00
And what about downloading the images of music through the app?

Le ven. 20 sept. 2024 à 20:51, khalil allani ***@***.***> a
écrit :

> Understood thank you regardless
>

**Comment by MSOB7YY** [comment] 2024-09-20 23:08
@Prokilo1987 https://github.com/namidaco/namida/issues/239#issuecomment-2195163594

**Comment by Prokilo1987** [comment] 2024-09-21 08:51
Yeah bro I remember those requests I made 😅
Has there been any progress on that task or task number 5?
Task 5 is making the song displays look larger when side by side and ur
scrolling down or up

**Comment by Prokilo1987** [comment] 2024-09-21 16:18
> 5. in that case he can already do this in `settings>customizations>album tile`
>    
>    * top right date > disable
>    * track number in album page > disable
> 
> @Prokilo1987 u can also just toggle the "grid" button in album/artist/genre/playlist pages, it will display 1 tile or 2, 3, 4 grids

It only works for albums and not tracks sadly, wish we could add this option but make tracks also in the same level not a "zigzag"

**Comment by Prokilo1987** [comment] 2024-09-23 09:14
Why bro, its literally the same code but apply it for tracks instead of
albums

**Comment by Prokilo1987** [comment] 2024-09-24 00:02
Hey bro, hope you're doing well, just wanted to give you an idea, if you
wanna add the album arts downloading feature, try running a collab with the
musicbrainz team, they already have a trained model and a huge library of
music arts, and they are fully open aource like namida, it could things a
lot faster and easier

Le lun. 23 sept. 2024 à 10:13, khalil allani ***@***.***> a
écrit :

> Why bro, its literally the same code but apply it for tracks instead of
> albums
>

**Comment by MSOB7YY** [comment] 2024-09-30 18:57
> Why bro, its literally the same code but apply it for tracks instead of
albums

its not just about the code, the general design would be heavily affected, a whole section inside customization settings will make no sense, the cusomization available for track tile cant be easily transfered to a grid card (in terms of design).
also this might be one of characteristics of namida, having tracks as grids is quite uhhh..
but anyways if we ever added this it would be for **tracks page** only. any other page won't be affected (due to the fact that many optimizations are based on 1 tile in the row, and due to namida would end up looking quite awful)

> wanna add the album arts downloading feature, try running a collab with the
musicbrainz team
ofc it would be from many sources including musicbrainz, thanks for suggestion. u can track here tho #5

**Closed** 2024-09-30 18:58 UTC

**Comment by Prokilo1987** [comment] 2024-10-02 21:01
Awesome, thanks for the update!
