### ISSUE TITLE
[ISSUE] Problems with letters in the Ukrainian translation

### ISSUE THREAD

**Issue by Andrew1397** [namidaco/namida#183] opened 2024-05-03 09:20 UTC
Letters such as "ґ", "ї", "і", "є" are replaced by the symbols shown in the photo. 
For example, I added all the problematic letters in the following line
![зображення](https://github.com/namidaco/namida-translations/assets/44724275/b267d453-8a79-4b69-9a82-f2acd843441e)
And this is how they appear in the program (You can also see these letters in words that are replaced by symbols)
![Screenshot_20240503-115524_Namida](https://github.com/namidaco/namida-translations/assets/44724275/fbe6b35b-01e5-4cee-94de-c94c7bfeea84)

**Comment by VerySweetBread** [comment] 2024-05-03 09:56
Duplicate of https://github.com/namidaco/namida-translations/issues/43

**Comment by MSOB7YY** [comment] 2024-05-03 10:55
@VerySweetBread @Andrew1397 it's most probably cuz of the font used "LexendDeca",  normally it should fallback to your system font idk whats going wrong

**Comment by BakaChocolate** [comment] 2024-05-07 22:59
Looks like it's for all non-latin characters? Mine can't show Japanese lyrics at all.
![Screenshot_20240507-235839_Namida](https://github.com/namidaco/namida/assets/20755237/8c66854c-dcf6-4863-b002-8203cb66962c)

**Comment by VerySweetBread** [comment] 2024-05-08 11:06
> Looks like it's for all non-latin characters? 

Yes, it's a Cyrillic. Problem is that Namida shows Cyrillic from Russian (А-Я+Ё), but doesn't from Ukrainian (+Ї, Є etc.)

> Mine can't show Japanese lyrics at all.

Depends on device as well
![Screenshot_20240508-135820](https://github.com/namidaco/namida/assets/33878951/190c2445-551f-403d-bc87-31be888727b7)

**Comment by MSOB7YY** [comment] 2024-05-08 21:18
fixed as mentioned guys

**Closed** 2024-05-08 21:17 UTC

**Comment by Andrew1397** [comment] 2024-05-10 19:57
> виправлено, як згадувалося, хлопці

Cool.  
Thank you very much. 
We will wait for the update
