### ISSUE TITLE
[FEATURE REQUEST] Can you make an app for the windows and pcs

### ISSUE THREAD

**Issue by User6899j** [namidaco/namida#313] opened 2024-08-06 19:09 UTC
I really like the ui and all the features on this app, i would love it if you could release an app on windows or Pcs

**Comment by MSOB7YY** [comment] 2024-08-07 16:54
thank you so so much, i personally would love this too and i find it useful but sadly its not so easy. many critical implementations are done only for android and alternatives for windows are not available. its not impossible but too much work so i have no plans for the near future. this is a duplicate of #282 tho

**Closed** 2024-08-07 16:54 UTC
