### ISSUE TITLE
funny

### ISSUE THREAD

**Issue by idontveapc** [namidaco/namida#103] opened 2024-01-08 10:49 UTC
- indexing songs in double –on my i reached 700+ songs.
- auto theme is dark theme –system dark mode was disabled and i cleared all the data but still theme is dark: 
![Screenshot_20240108-122439](https://github.com/namidaco/namida/assets/122597295/e62ff204-9c4d-4edd-b08d-9d190911b403)

**Comment by MSOB7YY** [comment] 2024-01-08 13:04
### this was also fixed in [v1.9.3](https://github.com/namidaco/namida/releases/tag/v1.9.3)

about theme option, it can happen mainly from android side, miui devices may have bugs like these, just restart the app and it should work

**Closed** 2024-01-08 13:04 UTC

**Comment by MSOB7YY** [comment] 2024-01-08 16:01
@idontveapc 
well the issue is that i havent touched this part since v1.8.5 or even earlier, if there is an issue it should have been there always

refer to https://github.com/namidaco/namida/commits/main/lib/controller/current_color.dart & https://github.com/namidaco/namida/commits/main/lib/ui/widgets/settings/theme_settings.dart

**Comment by MSOB7YY** [comment] 2024-01-08 18:04
as mentioned, just fixed
thanks for reporting
